### ISSUE TITLE
OpenEMR on GCP

### ISSUE THREAD

**Issue by MatthewVita** [openemr/openemr-devops#146]
_(I will separate out everything into proper GH issues - just leaving it all in one place before we start so that everyone is on the same page :+1:)_

# Goal

OpenEMR team to work with Google GCP to get a containerized, secure, and compliant deployment of OpenEMR up and running.

# People

Google:
- Erik Gomez, Solutions Engineer

OpenEMR:
- Asher Densmore-Lynn (@jesdynf): Architect
- Dr. Brady Miller (@bradymiller): Technical Lead
- Matthew Vita (@matthewvita): Project Manager, QA

# Tasks

- [x] Kick off call
- [x] Matthew to send an introduction email after the holiday
- [x] Matthew to suggest meeting times for our every-other-week meeting
- [ ] All to meet (medium: TBD)
- [ ] Determine demo/seed data needs
- [ ] Identify all managed services and GCP-centric DevOps tools to use/trial
- [ ] Determine comparable AWS package (for context, please see https://www.open-emr.org/blog/post/openemr-offers-panel-of-turn-key-solutions-with-amazons-cloud-services/)
- [ ] Discuss FHIR needs/use cases
- [ ] (internal) Catch up on the latest GCP best practices (orchestration/config mgmt./encryption/storage/backups/availability/etc)
- [ ] (internal) Consider what an Nginx-centric deployment would look like
- [ ] Create or find a CouchDB solution

**Comment by bradymiller** [comment]
Regarding nginx,
This has recently been done. Can see the process here:
https://github.com/openemr/openemr/issues/1696

This nginx/php-fpm solution has been dockerized, redis'd, and docker swarmed:
https://community.open-emr.org/t/openemr-official-docker-has-been-released/9084/12
https://github.com/openemr/openemr/blob/master/contrib/util/docker/README.md#setup (see step 3)
https://community.open-emr.org/t/docker-openemr-swarm/10426

**Comment by bradymiller** [comment]
Regarding CouchDB,
This is super easy to set up within the docker development environment:
https://github.com/openemr/openemr/blob/master/contrib/util/docker/README.md#couchdb

**Comment by danehrlich1** [comment]
@MatthewVita I have submitted the beginnings of Kubernetes to this repo. That project will be made to run on GCP (and anywhere else) when done.

The first goal though is to get the Docker-Compose / Swarm thing up and running. It's not much different from what we already have except it has a cool WAF container running in front of everything.
